CREATE VIEW BURI_PATH_HISTORY_DATA_USER AS 
SELECT
	BURI_PATH_DATA.PATH_ID AS PATH_ID,
	BURI_PATH_DATA.PATH_NAME AS PATH_NAME,
	BURI_PATH_DATA.REAL_PATH_NAME AS REAL_PATH_NAME,
	BURI_PATH_DATA.PATH_TYPE AS PATH_TYPE,
	BURI_PATH_DATA.PKEY_NUM AS PKEY_NUM,
	BURI_PATH_DATA.PKEY_VAL AS PKEY_VAL,
	BURI_PATH_DATA.DATA_TYPE AS DATA_TYPE,
	BURI_PATH_DATA.TABLE_NAME AS TABLE_NAME,
	BURI_PATH_DATA.DATA_ID AS DATA_ID,
	BURI_PATH_DATA.STATE_ID AS STATE_ID,
	BURI_PATH_DATA.AUTO_RUN_TIME AS AUTO_RUN_TIME,
	BURI_PATH_DATA.INSERT_DATE AS INSERT_DATE,
	BURI_PATH_DATA.PROCESS_DATE AS PROCESS_DATE,
	BURI_PATH_DATA.ABORT_DATE AS ABORT_DATE,
	BURI_PATH_DATA.PARTICIPANT_NAME AS PARTICIPANT_NAME,
	BURI_PATH_DATA.PARTICIPANT_TYPE AS PARTICIPANT_TYPE,
	BURI_USER.BURI_USER_ID AS BURI_USER_ID,
	BURI_USER.USER_ID_VAL AS USER_ID_VAL,
	BURI_USER.USER_ID_NUM AS USER_ID_NUM
FROM
	BURI_PATH_HISTORY_DATA AS BURI_PATH_DATA,
	BURI_STATE_USER,
	BURI_USER
WHERE
	BURI_PATH_DATA.STATE_ID = BURI_STATE_USER.STATE_ID
	AND BURI_USER.BURI_USER_ID = BURI_STATE_USER.BURI_USER_ID
	AND BURI_STATE_USER.DELETE_DATE > CURRENT_TIMESTAMP
;