SELECT
	BURI_PATH.PATH_ID,
	BURI_PATH.PATH_NAME,
	BURI_PATH.REAL_PATH_NAME
FROM
	BURI_STATE,
	BURI_PATH
WHERE
	BURI_STATE.PATH_ID = BURI_PATH.PATH_ID
	AND BURI_STATE.DATA_ID = /*dataId*/1
	AND PROCESS_DATE > CURRENT_TIMESTAMP
;
