SELECT 
	BURI_PATH.*
FROM
	BURI_PATH,
	BURI_STATE,
	BURI_DATA
WHERE
	BURI_PATH.PATH_ID = BURI_STATE.PATH_ID
	AND BURI_DATA.DATA_ID = BURI_STATE.DATA_ID
	AND PATH_NAME LIKE /*path*/'pathName.path.path'
	AND BURI_DATA.DATA_ID = /*dataId*/1
	/*IF pathType != null */AND BURI_PATH.PATH_TYPE = /*pathType*/1 /*END*/
	AND BURI_STATE.PROCESS_DATE > CURRENT_TIMESTAMP
;
