SELECT
	count(*)
FROM
	BURI_STATE,
	BURI_BRANCH
where
	BURI_BRANCH.BRANCH_ID = BURI_STATE.BRANCH_ID
	AND BURI_BRANCH.PARENT_BRANCH_ID = /*branchId*/1
	AND BURI_STATE.PROCESS_DATE > CURRENT_TIMESTAMP
;
