UPDATE
	BURI_STATE
SET
	PROCESS_DATE = CURRENT_TIMESTAMP,
	ABORT_DATE = CURRENT_TIMESTAMP
WHERE
	PROCESS_DATE > CURRENT_TIMESTAMP
	AND BRANCH_ID IN ( 
		SELECT
			BRANCH_ID
		FROM
			BURI_BRANCH
		WHERE
			PARENT_BRANCH_ID = /*branchId*/1
		)
;
