drop view IF EXISTS BuriPathDataUser;

drop view IF EXISTS BuriPathData;

drop view IF EXISTS BuriPathHistoryDataUser;

drop view IF EXISTS BuriPathHistoryData;


DROP TABLE IF EXISTS BuriStateUser CASCADE;

DROP SEQUENCE IF EXISTS BuriStateUserID;

DROP TABLE IF EXISTS BuriState CASCADE;

DROP SEQUENCE IF EXISTS BuriStateID;

DROP TABLE IF EXISTS BuriStateUndoLog CASCADE;

DROP SEQUENCE IF EXISTS BuriStateUndoLogID;

DROP TABLE IF EXISTS BuriTransaction CASCADE;

DROP SEQUENCE IF EXISTS BuriTransactionID;

DROP TABLE IF EXISTS BuriBranch CASCADE;

DROP SEQUENCE IF EXISTS BuriBranchID;

DROP TABLE IF EXISTS BuriDataPathHistory CASCADE;

DROP SEQUENCE IF EXISTS BuriDataPathHistoryID;

DROP TABLE IF EXISTS BuriData CASCADE;

DROP SEQUENCE IF EXISTS BuriDataID;

DROP TABLE IF EXISTS BuriPath CASCADE;

DROP SEQUENCE IF EXISTS BuriPathID;

DROP TABLE IF EXISTS BuriUser CASCADE;

DROP SEQUENCE IF EXISTS BuriUserID;

