CREATE TABLE Document (
	id BIGINT NOT NULL,
	title VARCHAR(100),
	contents VARCHAR(1024),
	processDate TIMESTAMP
);

CREATE SEQUENCE DocumentID
START WITH 1
INCREMENT BY 1
;

ALTER TABLE Document ADD PRIMARY KEY(id);

CREATE INDEX XF1Document ON Document (
	id ASC
);

CREATE TABLE Role (
	id BIGINT NOT NULL,
	name VARCHAR(100),
	processDate TIMESTAMP
);

CREATE SEQUENCE RoleID
START WITH 1
INCREMENT BY 1
;

ALTER TABLE Role ADD PRIMARY KEY(id);

CREATE INDEX XF1Role ON Role (
	id ASC
);
