INSERT INTO BURI_STATE_UNDO_LOG 
(
	STATE_ID,
	PATH_ID,
	DATA_ID,
	BRANCH_ID,
	USER_ID_VAL,
	USER_ID_NUM,
	BT_ID,
	CREATE_BT_ID,
	INSERT_DATE,
	AUTO_RUN_TIME,
	PROCESS_DATE,
	ABORT_DATE,
	VERSION_NO
)
SELECT
	STATE_ID,
	PATH_ID,
	DATE_ID,
	BRANCH_ID,
	USER_ID_VAL,
	USER_ID_NUM,
	/*btId*/1,
	BT_ID,
	INSERT_DATE,
	AUTO_RUN_TIME,
	PROCESS_DATE,
	ABORT_DATE,
	VERSION_NO
FROM
	BURI_STATE
/*BEGIN*/WHERE
	/*IF stateId != 0 */STATE_ID = /*stateId*/1 /*END*/
	/*IF branchId != 0 */AND BRANCH_ID = /*branchId*/1 /*END*/
/*END*/
