CREATE VIEW BURI_PATH_DATA AS
SELECT
	BURI_PATH.PATH_ID AS PATH_ID,
	BURI_PATH.PATH_NAME AS PATH_NAME,
	BURI_PATH.REAL_PATH_NAME AS REAL_PATH_NAME,
	BURI_PATH.PATH_TYPE AS PATH_TYPE,
	BURI_DATA.PKEY_NUM AS PKEY_NUM,
	BURI_DATA.PKEY_VAL AS PKEY_VAL,
	BURI_DATA.DATA_TYPE AS DATA_TYPE,
	BURI_DATA.TABLE_NAME AS TABLE_NAME,
	BURI_DATA.DATA_ID AS DATA_ID,
	BURI_STATE.STATE_ID AS STATE_ID,
	BURI_STATE.AUTO_RUN_TIME AS AUTO_RUN_TIME,
	BURI_STATE.PARTICIPANT_NAME AS PARTICIPANT_NAME,
	BURI_STATE.PARTICIPANT_TYPE AS PARTICIPANT_TYPE
FROM
	BURI_PATH,
	BURI_STATE,
	BURI_DATA
WHERE
	BURI_PATH.PATH_ID = BURI_STATE.PATH_ID
	AND BURI_DATA.DATA_ID = BURI_STATE.DATA_ID
	AND BURI_STATE.PROCESS_DATE > CURRENT_TIMESTAMP
;