CREATE TABLE Customer (
       customerId	INTEGER NOT NULL generated by default 
				AS IDENTITY( START WITH 1, INCREMENT BY 1),
       customerCode			VARCHAR(100) NOT NULL,
       customerName			VARCHAR(100) NOT NULL,
       mailAddress			VARCHAR(100) NOT NULL,
       PRIMARY KEY (customerId)
);
CREATE INDEX IdxCustomerCode ON Customer
(
       customerCode                   ASC
);



CREATE TABLE MeterCheck (
       meterCheckId	INTEGER NOT NULL generated by default 
				AS IDENTITY( START WITH 1, INCREMENT BY 1),
       meterCheckDate			TIMESTAMP NOT NULL,
       meterIndication			INTEGER NOT NULL,
       billCode				VARCHAR(100),
       billAmount			INTEGER,
       paymentAmount		INTEGER,
       customerId				INTEGER,
       PRIMARY KEY (meterCheckId)
);
ALTER TABLE MeterCheck
       ADD FOREIGN KEY (customerId)
                             REFERENCES Customer
                             ON DELETE SET NULL;
CREATE INDEX IdxBillCode ON MeterCheck
(
       billCode                   ASC
);
