SELECT 
	BURI_PATH_DATA.PATH_ID,
	BURI_PATH_DATA.PATH_NAME,
	BURI_PATH_DATA.DATA_ID,
	BURI_PATH_DATA.PKEY_VAL,
	BURI_PATH_DATA.PKEY_NUM,
	BURI_PATH_DATA.DATA_TYPE,
	BURI_PATH_DATA.REAL_PATH_NAME,
	BURI_PATH_DATA.PATH_TYPE,
	BURI_PATH_DATA.STATE_ID,
	BURI_PATH_DATA.AUTO_RUN_TIME
FROM
	BURI_PATH_DATA
WHERE
	AUTO_RUN_TIME < SYSDATE
